memory_limit = 512M

upload_max_filesize = 200M
post_max_size = 210M
max_file_uploads = 50

max_execution_time = 300
max_input_time = 300
max_input_vars = 5000

date.timezone = Europe/Moscow
expose_php = Off

opcache.enable = 1
opcache.enable_cli = 0
opcache.memory_consumption = 192
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 20000
opcache.validate_timestamps = 0
opcache.save_comments = 1

realpath_cache_size = 4096k
realpath_cache_ttl = 600
